import math
attempts = input("How many attempts?")
implicit = input("How many implicits?")
print(implicit, ",",  attempts)
d = (.25 ** int(implicit))
c = (int(attempts) - int(implicit))
e = (.75 ** int(c))
a = (d * e)
fx = math.factorial(int(attempts))
fj = math.factorial(int(implicit))
fxj = math.factorial(int(attempts) - int(implicit))
b = (fx) / (fj * fxj)
print(a * b)
